import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import TodoContextProvider from "@/context/TodoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo Next App",
  description: "Generated by create next app by Jitendriya Meher",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar></Navbar>
        <TodoContextProvider>
          {children}
        </TodoContextProvider>
      </body>
    </html>
  );
} 
